version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'dev'
    schedule:
      interval: 'daily'
    ignore:
      # Ignore remix and react packages, we'll bump those manually
      - dependency-name: '*remix*'
      - dependency-name: '*react*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    target_branch: 'dev'
    schedule:
      interval: 'weekly'
