name: Validate
on:
  pull_request: {}
  workflow_call: {}

concurrency:
  group: validate-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

  lint:
    needs: setup
    name: ⬣ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install deps
        run: npm ci

      - name: 🖼 Build icons
        run: npm run build:icons --verbose

      - name: 🔬 Lint
        run: npm run lint

  build:
    needs: setup
    name: 🔨 Build
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

  typecheck:
    needs: setup
    name: ʦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install deps
        run: npm ci

      - name: Generate prisma client
        run: npx prisma generate

      - name: 🖼 Build icons
        run: npm run build:icons

      - name: Show TypeScript version
        run: npx tsc --version

      - name: 🔎 Type check
        run: npm run typecheck

  vitest:
    needs: setup
    name: ⚡ Vitest
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install deps
        run: npm ci

      - name: 🏄 Copy test env vars
        run: cp .env.example .env

      - name: 🖼 Build icons
        run: npm run build:icons

      - name: ⚡ Run vitest
        run: npm run test -- --coverage

  # Having trouble with playwright job, commenting it out for now as we're not doing much e2e testing atm
  # playwright:
  #   needs: setup
  #   name: 🎭 Playwright
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 60
  #   steps:
  #     - name: ⬇️ Checkout repo
  #       uses: actions/checkout@v4

  #     - name: 🏄 Copy test env vars
  #       run: cp .env.example .env

  #     - name: ⎔ Setup node
  #       uses: actions/setup-node@v6
  #       with:
  #         node-version: 22

  #     - name: 📥 Restore cache
  #       uses: actions/cache/restore@v4
  #       with:
  #         path: |
  #           node_modules
  #           node_modules/.prisma
  #         key: node-deps-${{ hashFiles('package-lock.json') }}

  #     - name: 📥 Install Playwright Browsers
  #       run: npm run test:e2e:install

  #     - name: 🛠 Setup Database
  #       run: npx prisma migrate deploy

  #     - name: 🏦 Cache Database
  #       id: db-cache
  #       uses: actions/cache@v4
  #       with:
  #         path: prisma/data.db
  #         key:
  #           db-cache-schema_${{
  #           hashFiles('./prisma/schema.prisma')}}-migrations_${{
  #           hashFiles('./prisma/migrations/*/migration.sql')}}

  #     - name: 🌱 Seed Database
  #       if: steps.db-cache.outputs.cache-hit != 'true'
  #       run: npx prisma migrate reset --force

  #     - name: 🏗 Build
  #       run: npm run build

  #     - name: 🎭 Playwright tests
  #       run: npx playwright test

  #     - name: 📊 Upload report
  #       uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: playwright-report
  #         path: playwright-report/
  #         retention-days: 30
